---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# Core libraries
library(tidyverse)
library(tidyquant)

#Interactive visualizations
library(plotly)


# Database
library(odbc)
library(RSQLite)
```

```{r}
con <- dbConnect(RSQLite::SQLite(),"../00_data/bikes_database.db")
#dbListTables(con)

bikes_tbl <- tbl(con, "bikes")
bikeshops_tbl <- tbl(con, "bikeshops")
orderlines_tbl <- tbl(con, "orderlines")

processed_data_tbl <- orderlines_tbl %>% 
    left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id")) %>% 
    left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>% 
    mutate(extended_price = quantity * price) %>% 
    collect()

processed_data_tbl <- processed_data_tbl %>% 
     mutate(order.date = ymd(order.date)) %>% 
    separate(location, into = c("city", "state"), sep = ", ") %>% 
    select(order.date, order.id, order.line, state, quantity, price, extended_price)

dbDisconnect(con)
    

```

Column {data-width=1000}
---------------------------------------------------------------------

###By State